// M2-016: the session production wiring, verified IN THE LOOP. The audit
// before this card found the production session calls only inside the
// PrototypeHUD debug exec: the game main loop never injected the session
// clock (the M2-008 wave pump never ran), RoomTrigger only StartRoom-ed
// without BeginWaves (entering the room spawned nothing), no enemy
// definition runtime asset existed, and RetryRoom/SetPlayer had no
// production caller (the HUD retry button refused for lack of context).
//
// This suite reproduces exactly that hole first (red) and then locks the
// wired production chain (green). The defining property of the suite: it
// NEVER injects a test clock. The session clock comes exclusively from the
// production wiring under test - APrototypeCharacter::Tick handing
// World->GetTimeSeconds() to URoomSessionSubsystem::SetSessionClockSeconds
// (the M1-041 input-clock injection point) - so every birth, the 0.3 s
// spawn slots, the 1.0 s inter-wave wait and the settlement elapse through
// the real game frame pump. The room definition comes from the trigger's
// own production defaults (the Data/rooms.json room_training_01 wave shape:
// 2 + 3 melee_grunt), the enemy definition from the real
// /Game/UEMMO/Enemy/Definitions/DA_melee_grunt asset (generated by
// Scripts/Editor/create_enemy_assets.py from Data/enemies.json), and the
// retry runs through the real HUD HandleRetryRequested path whose context
// the trigger handed over at room entry.
//
// Every kill flows through the legal lethal path only (the health
// component's public ApplyDamage, whose OnDied reaches the spawner death
// binding and from there the session bookkeeping). Scaffolding reuses the
// engine FTestWorldWrapper precedent (GameCombatWiringTests/RoomScenarioTests)
// with uniquely prefixed M2_016 symbols.
#include "Misc/AutomationTest.h"
#include "UObject/Package.h"
#include "UObject/UObjectGlobals.h"

#include "../Combat/HealthComponent.h"
#include "../Enemy/EnemyDefinition.h"
#include "../Enemy/MeleeEnemy.h"
#include "../PrototypeCharacter.h"
#include "../PrototypeHUD.h"
#include "../Room/RoomDefinition.h"
#include "../Room/RoomSessionSubsystem.h"
#include "../Room/RoomTrigger.h"

#include "Components/BoxComponent.h"
#include "Components/CapsuleComponent.h"
#include "Engine/CollisionProfile.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Tests/AutomationCommon.h"

#if WITH_DEV_AUTOMATION_TESTS

namespace UE::UEMMO::Tasks::M2_016
{
	// Fixed simulated frame step (60 fps like the design frame clock). The
	// world is driven ONLY through real ticks; the session clock is never
	// injected by this suite.
	constexpr float M2_016_FrameSeconds = 1.0f / 60.0f;

	// The floor: top face exactly at z=0 so the Data/rooms.json spawn heights
	// (z=88) drop the enemies a short way onto the floor, like the arena maps.
	const FVector M2_016_FloorCenter(300.0, 0.0, -100.0);
	const FVector M2_016_FloorHalfExtent(2200.0, 1500.0, 100.0);

	// Player start far outside the activation volume; the trigger volume
	// covers x in [-250, 50] around (-100, 0, 88) (the production default
	// placement of L_CombatRoom01).
	const FVector M2_016_PlayerOutside(-800.0, 0.0, 120.0);
	const FVector M2_016_PlayerInside(-100.0, 0.0, 120.0);
	const FVector M2_016_TriggerLocation(-100.0, 0.0, 88.0);

	// The wave spawn locations of the trigger's default wave data (the
	// Data/rooms.json room_training_01 shape: wave 0 two, wave 1 three). The
	// suite pins these so the trigger's production defaults stay the catalog
	// shape; births must land at or near one of them.
	const FVector M2_016_Wave0Locations[2] = {
		FVector(300.0, 0.0, 88.0),
		FVector(450.0, -150.0, 88.0)
	};
	const FVector M2_016_Wave1Locations[3] = {
		FVector(600.0, 100.0, 88.0),
		FVector(750.0, -100.0, 88.0),
		FVector(0.0, 300.0, 88.0)
	};

	// Loose birth-location band (cm): a spawned capsule settles a few
	// centimetres onto the floor; the band still catches gross mis-spawns.
	constexpr double M2_016_BirthLocationBandCm = 300.0;

	// The spawn slot interval and the inter-wave gap (the M2-007/M2-008
	// production constants the character-clock pump rides on) plus the
	// assertion band around a 0.3 s slot observed on the real frame clock.
	constexpr double M2_016_SpawnSlotSeconds = 0.3;
	constexpr double M2_016_SlotBandLowSeconds = 0.2;
	constexpr double M2_016_SlotBandHighSeconds = 0.5;
	constexpr double M2_016_WaveGapSeconds = 1.0;

	// Enemy asset generated by Scripts/Editor/create_enemy_assets.py from
	// Data/enemies.json (the melee_grunt row).
	const TCHAR* M2_016_EnemyAssetPath =
		TEXT("/Game/UEMMO/Enemy/Definitions/DA_melee_grunt.DA_melee_grunt");

	// World-static blocking box (the M2-010/M2-014 floor builder shape).
	static AActor* M2_016_SpawnBoxActor(UWorld& World, const FVector& Center,
		const FVector& HalfExtent, const TCHAR* Name)
	{
		FActorSpawnParameters Params;
		AActor* Actor = World.SpawnActor<AActor>(AActor::StaticClass(), Center, FRotator::ZeroRotator, Params);
		if (Actor == nullptr)
		{
			return nullptr;
		}
		UBoxComponent* Box = NewObject<UBoxComponent>(Actor, Name);
		Actor->SetRootComponent(Box);
		Box->SetMobility(EComponentMobility::Movable);
		Box->SetBoxExtent(HalfExtent);
		Box->SetCollisionProfileName(UCollisionProfile::BlockAll_ProfileName);
		Box->RegisterComponent();
		Box->SetWorldLocation(Center);
		return Actor;
	}

	// Spawns the real prototype pawn above the floor and lets it settle with
	// real physics and no controller (the M2-010/M2-014 rig).
	static APrototypeCharacter* M2_016_SpawnPlayer(UWorld& World, const FVector& Location)
	{
		FActorSpawnParameters Params;
		APrototypeCharacter* Player = World.SpawnActor<APrototypeCharacter>(
			APrototypeCharacter::StaticClass(), Location, FRotator::ZeroRotator, Params);
		if (Player == nullptr)
		{
			return nullptr;
		}
		if (UCharacterMovementComponent* Movement = Player->GetCharacterMovement())
		{
			Movement->bRunPhysicsWithNoController = true;
			if (!Movement->IsActive())
			{
				Movement->Activate(/*bReset*/ true);
			}
			if (Movement->MovementMode == MOVE_None)
			{
				Movement->SetDefaultMovementMode();
			}
		}
		return Player;
	}

	// The in-loop scene: real world, real session, real trigger, real pawn,
	// real HUD - and NO test clock anywhere. All timing comes from the
	// world ticks through the production character-tick session injection.
	struct FM2_016_Scene
	{
		FTestWorldWrapper Wrapper;
		UWorld* World = nullptr;
		URoomSessionSubsystem* Session = nullptr;
		ARoomTrigger* Trigger = nullptr;
		APrototypeCharacter* Player = nullptr;
		APrototypeHUD* Hud = nullptr;

		// Session event counters (the assertions read these only).
		int32 StartedCount = 0;
		int32 EndedCount = 0;
		TArray<FRoomResult> EndedResults;
		int32 PlayerDiedCount = 0;

		// Spawn sampling: the world-clock time each newly seen enemy first
		// appeared at, and the enemies already killed (corpses never shadow a
		// fresh kill target).
		TArray<double> EnemySpawnTimes;
		TArray<TWeakObjectPtr<AActor>> KilledEnemies;

		bool Build(FAutomationTestBase& Test)
		{
			if (!Test.TestTrue(TEXT("the test world is created (engine FTestWorldWrapper precedent)"),
				Wrapper.CreateTestWorld(EWorldType::Game)))
			{
				return false;
			}
			World = Wrapper.GetTestWorld();
			if (!Test.TestNotNull(TEXT("the test world is available"), World))
			{
				return false;
			}
			if (!Test.TestTrue(TEXT("play begins in the test world (full actor initialization)"),
				Wrapper.BeginPlayInTestWorld()))
			{
				return false;
			}
			Session = World->GetSubsystem<URoomSessionSubsystem>();
			if (!Test.TestNotNull(TEXT("the room session subsystem exists in the test world"), Session))
			{
				return false;
			}
			Session->OnRunStarted().AddLambda([this]()
			{
				++StartedCount;
			});
			Session->OnRunEnded().AddLambda([this](const FRoomResult& Result)
			{
				++EndedCount;
				EndedResults.Add(Result);
			});

			if (M2_016_SpawnBoxActor(*World, M2_016_FloorCenter, M2_016_FloorHalfExtent,
				TEXT("M2_016_Floor")) == nullptr)
			{
				Test.AddError(TEXT("the floor failed to spawn"));
				return false;
			}
			// A hand-built world never runs the map-load collision tree pass;
			// build it once before the first tick (the M1-041 pattern).
			World->EnsureCollisionTreeIsBuilt();

			// The HUD spawns like the game mode spawns it; its BeginPlay binds
			// the session's OnRunEnded (the M2-012 result-screen path).
			FActorSpawnParameters HudParams;
			Hud = World->SpawnActor<APrototypeHUD>(APrototypeHUD::StaticClass(),
				FVector::ZeroVector, FRotator::ZeroRotator, HudParams);
			if (!Test.TestNotNull(TEXT("the prototype HUD spawns in the test world"), Hud))
			{
				return false;
			}

			// The production trigger at its production default location; the
			// suite changes none of its defaults (the wiring under test reads
			// exactly the values the real map's trigger carries).
			FActorSpawnParameters TriggerParams;
			Trigger = World->SpawnActor<ARoomTrigger>(
				ARoomTrigger::StaticClass(), M2_016_TriggerLocation, FRotator::ZeroRotator, TriggerParams);
			if (!Test.TestNotNull(TEXT("the room trigger spawns"), Trigger)
				|| !Test.TestNotNull(TEXT("the trigger carries an activation volume"), Trigger->GetActivationVolume()))
			{
				return false;
			}
			if (!Test.TestTrue(TEXT("the trigger session resolves through the world"),
				Trigger->GetSession() == Session))
			{
				return false;
			}

			Player = M2_016_SpawnPlayer(*World, M2_016_PlayerOutside);
			if (!Test.TestNotNull(TEXT("the real prototype character spawns"), Player))
			{
				return false;
			}
			Player->PlayerDied.AddLambda([this]()
			{
				++PlayerDiedCount;
			});
			return true;
		}

		/** Ticks the world once; the ONLY time source of this suite. */
		bool TickSeconds(FAutomationTestBase& Test, float DeltaSeconds)
		{
			return Test.TestTrue(TEXT("the test world ticks"), Wrapper.TickTestWorld(DeltaSeconds));
		}

		/**
		 * Advances the world by real 60 fps ticks and samples the spawn book
		 * after every tick. No SetSessionClockSeconds call exists anywhere in
		 * this suite - the session clock moves only through the production
		 * character-tick injection.
		 */
		bool AdvanceSeconds(FAutomationTestBase& Test, double Seconds)
		{
			const double StepSeconds = static_cast<double>(M2_016_FrameSeconds);
			double Remaining = Seconds;
			while (Remaining > 1e-9)
			{
				const double StepNow = FMath::Min(StepSeconds, Remaining);
				if (!TickSeconds(Test, M2_016_FrameSeconds))
				{
					return false;
				}
				Remaining -= StepNow;
				SampleSpawns();
			}
			return true;
		}

		/** Records the world-clock time of every newly seen melee enemy. */
		void SampleSpawns()
		{
			if (World == nullptr)
			{
				return;
			}
			int32 Seen = 0;
			for (TActorIterator<AMeleeEnemy> It(World); It; ++It)
			{
				(void)*It;
				++Seen;
			}
			while (EnemySpawnTimes.Num() < Seen)
			{
				EnemySpawnTimes.Add(World->GetTimeSeconds());
			}
		}

		/** Teleports the player and ticks so the overlap state settles, then refreshes the volume query. */
		bool MoveAndTick(FAutomationTestBase& Test, const FVector& Location)
		{
			Player->SetActorLocation(Location, /*bSweep*/ false);
			if (!TickSeconds(Test, M2_016_FrameSeconds) || !TickSeconds(Test, M2_016_FrameSeconds))
			{
				return false;
			}
			Player->GetCapsuleComponent()->UpdateOverlaps();
			SampleSpawns();
			return true;
		}

		/** Alive melee enemies (corpses deliberately not counted). */
		int32 AliveEnemies() const
		{
			int32 Count = 0;
			for (TActorIterator<AMeleeEnemy> It(World); It; ++It)
			{
				UHealthComponent* Health = It->GetHealthComponent();
				if (Health != nullptr && Health->IsAlive())
				{
					++Count;
				}
			}
			return Count;
		}

		/** Every melee enemy actor in the world including corpses. */
		int32 TotalEnemies() const
		{
			int32 Count = 0;
			for (TActorIterator<AMeleeEnemy> It(World); It; ++It)
			{
				++Count;
			}
			return Count;
		}

		/**
		 * Kills every alive melee enemy through the legal lethal path (the
		 * health component's ApplyDamage; the death flows through the spawner
		 * death binding into the session bookkeeping) and registers each as
		 * processed.
		 */
		bool KillAllAliveEnemies(FAutomationTestBase& Test)
		{
			TArray<AMeleeEnemy*> Targets;
			for (TActorIterator<AMeleeEnemy> It(World); It; ++It)
			{
				AMeleeEnemy* Enemy = *It;
				UHealthComponent* Health = (Enemy != nullptr) ? Enemy->GetHealthComponent() : nullptr;
				if (Health != nullptr && Health->IsAlive())
				{
					Targets.Add(Enemy);
				}
			}
			for (AMeleeEnemy* Enemy : Targets)
			{
				if (!Test.TestTrue(
					FString::Printf(TEXT("the enemy %s accepts the lethal damage"), *Enemy->GetName()),
					Enemy->GetHealthComponent()->ApplyDamage(9999.0f) > 0.0f))
				{
					return false;
				}
				KilledEnemies.Add(Enemy);
			}
			return true;
		}

		/** True when every enemy seen so far was born at or near a configured wave location. */
		bool AllBirthsNearConfiguredLocations(FString& OutDetail) const
		{
			int32 Index = 0;
			for (TActorIterator<AMeleeEnemy> It(World); It; ++It)
			{
				AMeleeEnemy* Enemy = *It;
				double BestDistSquared = TNumericLimits<double>::Max();
				for (const FVector& Location : M2_016_Wave0Locations)
				{
					BestDistSquared = FMath::Min(BestDistSquared,
						FVector::DistSquared(Enemy->GetActorLocation(), Location));
				}
				for (const FVector& Location : M2_016_Wave1Locations)
				{
					BestDistSquared = FMath::Min(BestDistSquared,
						FVector::DistSquared(Enemy->GetActorLocation(), Location));
				}
				if (BestDistSquared > M2_016_BirthLocationBandCm * M2_016_BirthLocationBandCm)
				{
					OutDetail = FString::Printf(TEXT("enemy #%d (%s) at %s is outside every configured spawn band"),
						Index + 1, *Enemy->GetName(), *Enemy->GetActorLocation().ToString());
					return false;
				}
				++Index;
			}
			return true;
		}
	};

	// Diagnostics for a failed spawn count: what the session and the world hold.
	static void M2_016_DumpSpawnState(FAutomationTestBase& Test, const FM2_016_Scene& Scene)
	{
		Test.AddInfo(FString::Printf(TEXT("session state=%d spawned=%d killed=%d wave=%d clock=%.3f"),
			static_cast<int32>(Scene.Session->GetState()),
			Scene.Session->GetSpawnedEnemyCount(),
			Scene.Session->GetKilledCount(),
			Scene.Session->GetCurrentWaveIndex(),
			Scene.Session->GetSessionClockSeconds()));
		Test.AddInfo(FString::Printf(TEXT("world melee actors=%d (alive %d), seen spawn events=%d"),
			Scene.TotalEnemies(), Scene.AliveEnemies(), Scene.EnemySpawnTimes.Num()));
	}

	// The Data/enemies.json melee_grunt values the DA asset must carry.
	struct FM2_016_EnemyExpectation
	{
		FName EnemyId = FName(TEXT("melee_grunt"));
		float MaxHP = 60.0f;
		float AttackPower = 0.0f;
		float MoveSpeed = 220.0f;
		float AttackRangeX = 160.0f;
		float AlignYTolerance = 35.0f;
		float TelegraphSeconds = 0.35f;
		float SpawnGraceSeconds = 0.5f;
		FName MeleeAttackId = FName(TEXT("light_01"));
	};
}

using namespace UE::UEMMO::Tasks::M2_016;

// 1. Acceptance: player entry into the activation volume starts a run and the
//    waves spawn WITHOUT any test clock and WITHOUT any debug exec - the
//    session clock advances only through the production character-tick
//    injection, the trigger's StartRoom hands the player to the session and
//    calls BeginWaves with its definition data, wave 0 births its two enemies
//    on the 0.3 s slots, the 1.0 s gap follows the last death on the same
//    clock, wave 1 births its three, and the last death clears the run
//    exactly once (OnRunEnded fired once, Cleared, five real kills).
IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FUEMMOTasksM2_016TriggerEntryAutoSpawnsWavesAndClearsOnRealFrameClock,
	"UEMMO.Tasks.M2_016.TriggerEntryAutoSpawnsWavesAndClearsOnRealFrameClock",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext | EAutomationTestFlags::EngineFilter)

bool FUEMMOTasksM2_016TriggerEntryAutoSpawnsWavesAndClearsOnRealFrameClock::RunTest(const FString& Parameters)
{
	FM2_016_Scene Scene;
	if (!Scene.Build(*this))
	{
		return true;
	}

	// Before any entry: the pawn already ticks, so the production injection
	// must have moved the session clock off zero while the session stays Idle
	// (no run, no enemies, no clock injection from this suite).
	if (!Scene.TickSeconds(*this, M2_016_FrameSeconds) || !Scene.TickSeconds(*this, M2_016_FrameSeconds))
	{
		return true;
	}
	Scene.SampleSpawns();
	TestTrue(TEXT("the session clock advanced through the production character tick before any entry"),
		Scene.Session->GetSessionClockSeconds() > 0.0);
	TestTrue(TEXT("the session stays Idle before the player enters"),
		Scene.Session->GetState() == ERoomSessionState::Idle);
	TestEqual(TEXT("no enemy exists before the entry"), Scene.TotalEnemies(), 0);

	// Player entry: the trigger starts the run through the session.
	if (!Scene.MoveAndTick(*this, M2_016_PlayerInside))
	{
		return true;
	}
	if (!TestTrue(TEXT("the player entry moved the session to Running"),
		Scene.Session->GetState() == ERoomSessionState::Running))
	{
		return true;
	}
	TestEqual(TEXT("exactly one run started"), Scene.StartedCount, 1);
	const uint64 RunId = Scene.Session->GetRunId();
	TestTrue(TEXT("the run id was assigned"), RunId != 0);

	// Wave 0: both enemies birth themselves on the session clock that the
	// character tick advances (slot 0 at the pump anchor, slot 1 at +0.3 s).
	if (!Scene.AdvanceSeconds(*this, 0.6))
	{
		return true;
	}
	TestEqual(TEXT("both wave-0 enemies birthed through the real frame clock"),
		Scene.Session->GetSpawnedEnemyCount(), 2);
	TestEqual(TEXT("both wave-0 enemies are alive in the world"), Scene.AliveEnemies(), 2);
	M2_016_DumpSpawnState(*this, Scene);
	if (!TestTrue(TEXT("the spawn events were sampled twice"), Scene.EnemySpawnTimes.Num() == 2))
	{
		return true;
	}
	if (!TestTrue(TEXT("the second enemy followed the first on the 0.3 s slot"),
		Scene.EnemySpawnTimes[1] - Scene.EnemySpawnTimes[0] >= M2_016_SlotBandLowSeconds
		&& Scene.EnemySpawnTimes[1] - Scene.EnemySpawnTimes[0] <= M2_016_SlotBandHighSeconds))
	{
		AddInfo(FString::Printf(TEXT("slot delta: %.4f s"),
			Scene.EnemySpawnTimes[1] - Scene.EnemySpawnTimes[0]));
		return true;
	}
	FString BirthDetail;
	if (!TestTrue(TEXT("every birth sits at or near a configured wave spawn location"),
		Scene.AllBirthsNearConfiguredLocations(BirthDetail)))
	{
		AddInfo(BirthDetail);
		return true;
	}

	// Kill both: the deaths flow through the legal path into the session.
	if (!Scene.KillAllAliveEnemies(*this))
	{
		return true;
	}
	TestEqual(TEXT("both wave-0 deaths were counted"), Scene.Session->GetKilledCount(), 2);
	TestTrue(TEXT("a fully dead wave 0 alone keeps the run Running"),
		Scene.Session->GetState() == ERoomSessionState::Running);

	// The 1.0 s inter-wave wait elapses on the same real frame clock, then
	// wave 1 births its three enemies.
	if (!Scene.AdvanceSeconds(*this, M2_016_WaveGapSeconds + 0.8))
	{
		return true;
	}
	TestEqual(TEXT("wave 1 started after the gap"), Scene.Session->GetCurrentWaveIndex(), 1);
	TestEqual(TEXT("all five enemies birthed for the run (2+3)"),
		Scene.Session->GetSpawnedEnemyCount(), 5);
	TestEqual(TEXT("exactly three wave-1 enemies are alive"), Scene.AliveEnemies(), 3);
	M2_016_DumpSpawnState(*this, Scene);

	// The last death clears: exactly one end event, Cleared, five real kills.
	if (!Scene.KillAllAliveEnemies(*this))
	{
		return true;
	}
	TestTrue(TEXT("the run is Cleared after the last wave-1 death"),
		Scene.Session->GetState() == ERoomSessionState::Cleared);
	TestEqual(TEXT("OnRunEnded fired exactly once"), Scene.EndedCount, 1);
	if (Scene.EndedResults.Num() == 1)
	{
		TestTrue(TEXT("the end result records Cleared"), Scene.EndedResults[0].bCleared);
		TestEqual(TEXT("the end result keeps the run id"), Scene.EndedResults[0].RunId, RunId);
		TestEqual(TEXT("the end result counts exactly the five real deaths"),
			Scene.EndedResults[0].KilledCount, 5);
	}
	TestTrue(TEXT("the cleared run is reward eligible"), Scene.Session->IsRewardEligible(RunId));
	TestEqual(TEXT("the world holds exactly the five spawned enemies"), Scene.TotalEnemies(), 5);
	return true;
}

// 2. Acceptance: the player death path - the registered pawn's death fails the
//    running run (no late spawns), and the REAL HUD retry path restarts it:
//    the trigger handed the retry context (room definition + enemy
//    definition) to the HUD at entry, so HandleRetryRequested executes the
//    production URoomRetryService flow (old run enemies destroyed, player
//    revived, fresh RunId, waves restarted through the same real frame clock).
IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FUEMMOTasksM2_016PlayerDeathFailsRunAndHudRetryRestartsWaves,
	"UEMMO.Tasks.M2_016.PlayerDeathFailsRunAndHudRetryRestartsWaves",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext | EAutomationTestFlags::EngineFilter)

bool FUEMMOTasksM2_016PlayerDeathFailsRunAndHudRetryRestartsWaves::RunTest(const FString& Parameters)
{
	FM2_016_Scene Scene;
	if (!Scene.Build(*this))
	{
		return true;
	}

	// Enter: the run starts and wave 0 generates (one born at the pump anchor,
	// the second still unborn - the 0.3 s slot has not elapsed).
	if (!Scene.MoveAndTick(*this, M2_016_PlayerInside))
	{
		return true;
	}
	if (!TestTrue(TEXT("the entry started the run"), Scene.Session->GetState() == ERoomSessionState::Running))
	{
		return true;
	}
	if (!Scene.AdvanceSeconds(*this, 0.2))
	{
		return true;
	}
	const uint64 OldRunId = Scene.Session->GetRunId();
	if (!TestTrue(TEXT("exactly the first wave-0 enemy was born before the death"),
		Scene.Session->GetSpawnedEnemyCount() == 1))
	{
		M2_016_DumpSpawnState(*this, Scene);
		return true;
	}

	// The player dies mid-wave: the run fails first-terminal-wins, the unborn
	// spawns are cancelled and nothing spawns late.
	if (!TestTrue(TEXT("the player health pool accepts the lethal damage"),
		Scene.Player->GetHealth()->ApplyDamage(9999.0f) > 0.0f))
	{
		return true;
	}
	TestTrue(TEXT("the player death failed the running run"),
		Scene.Session->GetState() == ERoomSessionState::Failed);
	TestEqual(TEXT("the player death broadcast fired exactly once"), Scene.PlayerDiedCount, 1);
	TestEqual(TEXT("the failure fired exactly one end event"), Scene.EndedCount, 1);
	if (Scene.EndedResults.Num() == 1)
	{
		TestTrue(TEXT("the end result records the failure"), !Scene.EndedResults[0].bCleared);
		TestEqual(TEXT("the failed run keeps its run id"), Scene.EndedResults[0].RunId, OldRunId);
	}
	if (!Scene.AdvanceSeconds(*this, 1.0))
	{
		return true;
	}
	TestEqual(TEXT("no late spawn happened after the failure"),
		Scene.Session->GetSpawnedEnemyCount(), 1);
	TestEqual(TEXT("no second end event fired while Failed"), Scene.EndedCount, 1);
	TestTrue(TEXT("the result screen was prepared by the death (HUD OnRunEnded path)"),
		Scene.Hud->HasRoomResultScreen());

	// The production retry: the HUD's Retry button path. The context the
	// trigger handed over must make the request executable (the pre-card
	// behavior was a refusal with the screen staying up).
	Scene.Hud->HandleRetryRequested();
	if (!TestTrue(TEXT("the HUD retry restarted the run (session Running again)"),
		Scene.Session->GetState() == ERoomSessionState::Running))
	{
		AddInfo(FString::Printf(TEXT("after retry: state=%d run=%llu"),
			static_cast<int32>(Scene.Session->GetState()), Scene.Session->GetRunId()));
		return true;
	}
	const uint64 NewRunId = Scene.Session->GetRunId();
	TestTrue(TEXT("the retry started a new, larger run id"), NewRunId > OldRunId);
	TestEqual(TEXT("the retry destroyed the failed run's registered enemies"),
		Scene.TotalEnemies(), 0);
	TestEqual(TEXT("the retry fired no extra end event"), Scene.EndedCount, 1);
	TestEqual(TEXT("exactly two runs started in total (first + retry)"), Scene.StartedCount, 2);
	TestTrue(TEXT("the retried run has the player registered again (revived, alive)"),
		Scene.Player->GetHealth() != nullptr && Scene.Player->GetHealth()->IsAlive());

	// The fresh run drives its own wave 0 through the same real frame clock.
	if (!Scene.AdvanceSeconds(*this, 0.6))
	{
		return true;
	}
	TestEqual(TEXT("the retried run's wave 0 birthed its two enemies again"),
		Scene.Session->GetSpawnedEnemyCount(), 2);
	TestEqual(TEXT("the retried run's enemies are alive in the world"), Scene.AliveEnemies(), 2);
	M2_016_DumpSpawnState(*this, Scene);
	return true;
}

// 3. Acceptance: the enemy definition runtime asset exists, loads in a plain
//    -game process and carries exactly the Data/enemies.json melee_grunt row
//    (the source of truth Scripts/Editor/create_enemy_assets.py generates
//    DA_melee_grunt from), and passes the single-entry validation.
IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FUEMMOTasksM2_016MeleeGruntAssetLoadsAndMatchesEnemiesJson,
	"UEMMO.Tasks.M2_016.MeleeGruntAssetLoadsAndMatchesEnemiesJson",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext | EAutomationTestFlags::EngineFilter)

bool FUEMMOTasksM2_016MeleeGruntAssetLoadsAndMatchesEnemiesJson::RunTest(const FString& Parameters)
{
	UEnemyDefinition* Def = LoadObject<UEnemyDefinition>(nullptr, M2_016_EnemyAssetPath);
	if (!TestNotNull(TEXT("the DA_melee_grunt asset loads (run Scripts/Editor/create_enemy_assets.py)"), Def))
	{
		return true;
	}

	// The Data/enemies.json melee_grunt row, field by field.
	FM2_016_EnemyExpectation Expected;
	TestTrue(TEXT("the asset's EnemyId matches enemies.json"), Def->EnemyId == Expected.EnemyId);
	TestTrue(TEXT("the asset's MaxHP matches enemies.json"),
		FMath::IsNearlyEqual(Def->MaxHP, Expected.MaxHP));
	TestTrue(TEXT("the asset's AttackPower matches enemies.json"),
		FMath::IsNearlyEqual(Def->AttackPower, Expected.AttackPower));
	TestTrue(TEXT("the asset's MoveSpeed matches enemies.json"),
		FMath::IsNearlyEqual(Def->MoveSpeed, Expected.MoveSpeed));
	TestTrue(TEXT("the asset's AttackRangeX matches enemies.json"),
		FMath::IsNearlyEqual(Def->AttackRangeX, Expected.AttackRangeX));
	TestTrue(TEXT("the asset's AlignYTolerance matches enemies.json"),
		FMath::IsNearlyEqual(Def->AlignYTolerance, Expected.AlignYTolerance));
	TestTrue(TEXT("the asset's TelegraphSeconds matches enemies.json"),
		FMath::IsNearlyEqual(Def->TelegraphSeconds, Expected.TelegraphSeconds));
	TestTrue(TEXT("the asset's SpawnGraceSeconds matches enemies.json"),
		FMath::IsNearlyEqual(Def->SpawnGraceSeconds, Expected.SpawnGraceSeconds));
	TestTrue(TEXT("the asset's MeleeAttackId matches enemies.json"),
		Def->MeleeAttackId == Expected.MeleeAttackId);

	// The single-entry validation of the definition module accepts the asset.
	FText ValidationError;
	TestTrue(TEXT("the loaded asset passes ValidateEnemyDefinition"),
		ValidateEnemyDefinition(*Def, ValidationError));
	if (!ValidationError.IsEmpty())
	{
		AddInfo(ValidationError.ToString());
	}
	return true;
}

#endif
