#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"

#include "../Items/ItemInstance.h"
#include "../Items/ItemDefinition.h"
#include "../Room/RoomResult.h"

#include "RewardService.generated.h"

class UProfileSubsystem;

/**
 * One settlement reward draft (interface contract section 8, M3-008). A draft
 * is created exactly once per SettlementId by URewardService::BeginReward and
 * lives in UProfileSubsystem::PendingRewards, so it survives every World
 * switch (the profile is a UGameInstanceSubsystem). Plain value struct on
 * purpose, like FItemInstance/FProfileSnapshot: the members are all engine
 * free value types and the save layer (M3-013) owns any serialized form.
 *
 * The item instances are PRE-GENERATED here (M3-007 FDropGenerator): the
 * random result is produced exactly once when the draft is created and a
 * retry of the settlement never re-rolls it. The claim into the inventory
 * (including the full-inventory retention rule) belongs to M3-009.
 */
struct FPendingReward
{
	/** Business identity of the settlement this draft belongs to; unique per run. */
	uint64 SettlementId = 0;

	/** XP granted by the settlement (design: 50 per cleared room). */
	int32 XP = 0;

	/** Pre-generated item instances; the roll happened once at draft time. */
	TArray<FItemInstance> Items;
};

/**
 * Result of one URewardService::BeginReward request (M3-008).
 *
 * Idempotency semantics (the task card allows merging "already applied" with
 * "return the original draft"; the merge is documented here and in the task
 * report):
 * - Applied: a new draft was created and stored in the profile.
 * - AlreadyApplied: the settlement was already processed. Two sub-cases:
 *   (a) a pending draft for the SettlementId already exists -> OutDraft
 *   carries the ORIGINAL draft unchanged (field-for-field identical, no
 *   re-roll, no second item); (b) the SettlementId was already claimed into
 *   the profile (AppliedSettlementIds, the M3-009 claim flow) -> OutDraft
 *   stays default (a claimed settlement no longer carries a pending draft).
 * - RejectedFailedResult / RejectedNoProfile / RejectedGeneration: nothing
 *   was stored, no random result was ever consumed.
 */
enum class ERewardBeginResult : uint8
{
	/** New draft created and stored in the profile's PendingRewards. */
	Applied,

	/** Settlement already processed: original pending draft returned, or no draft when already claimed. */
	AlreadyApplied,

	/** The FRoomResult is Failed (not reward eligible); never any draft. */
	RejectedFailedResult,

	/** No bound profile subsystem or no existing profile to hold the draft. */
	RejectedNoProfile,

	/** FDropGenerator rejected its inputs (Error names the offending field). */
	RejectedGeneration
};

/** Outcome of one BeginReward request: result enum, draft copy, error text. */
struct FRewardBeginOutcome
{
	/** What happened; check Error on the rejected paths. */
	ERewardBeginResult Result = ERewardBeginResult::RejectedNoProfile;

	/**
	 * The draft: the newly created one for Applied, the unchanged ORIGINAL
	 * draft for the AlreadyApplied-with-pending-draft sub-case, default
	 * (empty) for every other result.
	 */
	FPendingReward Draft;

	/** Empty on Applied/AlreadyApplied; names the rejection reason otherwise. */
	FString Error;
};

/**
 * M3-008: settlement reward drafts with idempotent application. An independent
 * UObject service (no World, no subsystem registration): it holds a weak
 * reference to the GameInstance-level UProfileSubsystem (BindProfile) and
 * writes the drafts through the profile's PendingRewards container, so a
 * draft outlives every World switch exactly like the profile itself.
 *
 * BeginReward(RoomResult, Catalog) turns one Cleared run result into a
 * pending draft: XP 50 (design constant RewardXPPerClear) plus exactly one
 * equipment instance generated by the M3-007 FDropGenerator from the pinned
 * starter drop table. Everything is deterministic:
 * - RewardSeed = DeriveRewardSeed(RoomResult.Seed): a fixed salted mix of the
 *   run's room seed - never a wall clock - so the same run always re-derives
 *   the same roll inputs and different runs derive different ones.
 * - InstanceId is a function of (SettlementId, RewardIndex) inside the
 *   generator, so the same settlement always maps to the same identity.
 * - A repeat BeginReward for the same SettlementId returns the ORIGINAL draft
 *   (AlreadyApplied) without generating again: the random result is produced
 *   exactly once per settlement and a retry never re-rolls it.
 * A Failed result is always rejected (the value-level IsRewardEligible=false
 * path) and never creates a draft. Different runs (different SettlementIds)
 * keep independent drafts.
 *
 * No disk persistence here (M3-013 owns the save layer) and no inventory
 * mutation (the claim, including full-inventory retention, belongs to M3-009).
 */
UCLASS()
class UEMMO_API URewardService : public UObject
{
	GENERATED_BODY()

public:
	// -- Design constants --------------------------------------------------------

	/** XP granted per cleared room's settlement (interface contract: XP 50). */
	static constexpr int32 RewardXPPerClear = 50;

	// -- Wiring ------------------------------------------------------------------

	/**
	 * Binds the GameInstance-level profile the drafts live in (weak reference;
	 * a destroyed subsystem is detected on use). Passing null unbinds.
	 */
	void BindProfile(UProfileSubsystem* Profile);

	/** The currently bound profile (nullptr when unbound or destroyed). */
	UProfileSubsystem* GetBoundProfile() const;

	// -- Seed derivation -----------------------------------------------------------

	/**
	 * RewardSeed = fixed-salt mix of the run's room Seed (FRoomResult.Seed).
	 * Pure and clock-free: the same RoomSeed always derives the same
	 * RewardSeed (a retry reproduces the identical draft), a different
	 * RoomSeed derives a different one. 64-bit murmur3 finalizer with a
	 * purpose-distinct salt, folded to int64; mirrors the FDropGenerator
	 * derivation style while never sharing its raw values.
	 */
	static int64 DeriveRewardSeed(int32 RoomSeed);

	// -- Settlement entry ----------------------------------------------------------

	/**
	 * Begins (or replays) the reward settlement of one finished run.
	 *
	 * - Failed result: rejected (RejectedFailedResult), no draft, no roll.
	 * - No bound profile / no profile: rejected (RejectedNoProfile).
	 * - SettlementId already claimed (AppliedSettlementIds, M3-009): AlreadyApplied
	 *   with a default draft - no draft, no re-roll.
	 * - SettlementId already has a pending draft: AlreadyApplied with the
	 *   ORIGINAL draft returned unchanged (idempotent replay, no re-roll).
	 * - Otherwise: one equipment piece from the starter table via
	 *   FDropGenerator::GenerateReward (RewardSeed from the room Seed,
	 *   SettlementId as the identity), stored as
	 *   FPendingReward{SettlementId, XP=50, Items[1]} in the profile's
	 *   PendingRewards; returns Applied with the new draft.
	 * Generation failure (broken table/catalog data): RejectedGeneration with
	 * the generator's field-naming error; nothing is stored.
	 */
	FRewardBeginOutcome BeginReward(const FRoomResult& Result, const FItemDefinitionCatalog& Catalog);

private:
	/** GameInstance-level profile holding PendingRewards; weak on purpose. */
	TWeakObjectPtr<UProfileSubsystem> ProfilePtr;
};
